---
# -- [ec2]
# -- local ansible_connection=local
ec2:
  hosts:
    oracleserver:
      ansible_host: 10.16.10.15
      ansible_user: ec2-user
      ansible_ssh_private_key_file: /home/vivek/.ssh/linode.id_ed25519.pub
