- name: Install Oracle in a Docker container
  ansible.builtin.shell: |
    docker volume create oracle_DB_volume
    docker login --username {{ username }} --password {{ password }} container-registry.oracle.com
    docker run -d --name oracle_DB -p 1521:1521 -p 8282:8282 -e ORACLE_PWD=Oralce_password123 -v oracle_DB_volume:/opt/oracle container-registry.oracle.com/database/enterprise
